include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: warning
  exclude:
    - .dart_tool/**
    - build/**
    - "**.freezed.dart"
    - "**.g.dart"
    - web/**

plugins:
  riverpod_lint: 3.1.9

linter:
  rules:
    - always_use_package_imports
    - directives_ordering

formatter:
  page_width: 120
  trailing_commas: preserve
